package com.swent.mapin.navigation

import android.net.Uri
import android.util.Log

/**
 * Handler for parsing and processing deep links in the application.
 *
 * This object handles incoming deep links with the "mapin://" scheme and converts them into
 * navigation routes that can be used by the app's navigation system. Deep links are used for push
 * notifications and external links to navigate users to specific screens within the app.
 *
 * **Supported deep link formats:**
 * - `mapin://friendRequests` -> Friends screen (Requests tab)
 * - `mapin://friendAccepted` -> Friends screen (Friends tab)
 * - `mapin://profile` -> Friends screen (Friends tab)
 * - `mapin://events` -> Map screen
 * - `mapin://messages` -> Chat screen
 * - `mapin://messages/{conversationId}` -> Specific conversation screen with dynamic ID
 * - `mapin://map` -> Map screen
 *
 * **Case Sensitivity:**
 * - The scheme ("mapin") matching is case-insensitive (handled by Android Uri.parse)
 * - Host names (e.g., "friendRequests", "messages") are case-sensitive in the when expression
 * - Path segments ({conversationId}) are passed as-is without case conversion
 *
 * **Dynamic Parameters:**
 * - `{conversationId}`: Extracted from the first path segment of the URI (e.g., in
 *   "mapin://messages/abc123", "abc123" becomes the conversationId)
 * - Parameters are URL-encoded when inserted into navigation routes to handle special characters
 * - If no conversationId is provided in messages deep link, navigates to general Chat screen
 *
 * **Route Handling:** Routes generated by this handler are consumed by AppNavHost for navigation.
 * The returned strings match the route patterns defined in the Route sealed class and registered
 * NavHost destinations.
 *
 * @see com.swent.mapin.navigation.AppNavHost Navigation graph that handles the generated routes
 * @see com.swent.mapin.navigation.Route Route definitions for the app's navigation destinations
 * @see com.swent.mapin.MainActivity Deep link entry point that uses this handler
 */
object DeepLinkHandler {

  /**
   * Parses a deep link string and returns the corresponding navigation route.
   *
   * This function validates the deep link scheme, extracts the host and path segments, and
   * constructs the appropriate navigation route string. Invalid or unrecognized deep links return
   * null and log a warning.
   *
   * **Examples:**
   *
   * ```
   * parseDeepLink("mapin://friendRequests") -> "friends?tab=REQUESTS"
   * parseDeepLink("mapin://messages/chat123") -> "conversation/chat123/Unknown"
   * parseDeepLink("mapin://messages") -> "chat"
   * parseDeepLink("https://example.com") -> null (invalid scheme)
   * parseDeepLink("mapin://unknown") -> null (unknown host)
   * ```
   *
   * @param deepLink The deep link URL to parse (e.g., "mapin://friendRequests")
   * @return The navigation route string if the deep link is valid, null otherwise
   * @throws None - All parsing exceptions are caught and logged, returning null on error
   */
  fun parseDeepLink(deepLink: String): String? {
    return try {
      val uri = Uri.parse(deepLink)

      if (uri.scheme != "mapin") {
        Log.w("DeepLinkHandler", "Invalid scheme: ${uri.scheme}")
        return null
      }

      when (uri.host) {
        "friendRequests" -> "friends?tab=REQUESTS"
        "friendAccepted",
        "profile" -> "friends?tab=FRIENDS"
        "events" -> Route.Map.route
        "messages" -> {
          val conversationId = uri.pathSegments.firstOrNull()
          if (conversationId != null) {
            "conversation/$conversationId/${Uri.encode("Unknown")}"
          } else {
            Route.Chat.route
          }
        }
        "map" -> Route.Map.route
        else -> {
          Log.w("DeepLinkHandler", "Unknown host: ${uri.host}")
          null
        }
      }
    } catch (e: Exception) {
      Log.e("DeepLinkHandler", "Parse error: $deepLink", e)
      null
    }
  }
}
