package com.swent.mapin.model.event

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Integration test for the production `EventsDatabase` class using an in-memory database. Verifies
 * the database exposes the DAO and that basic operations succeed. Generated by AI.
 */
@RunWith(AndroidJUnit4::class)
class EventsDatabaseIntegrationTest {
  private lateinit var db: EventsDatabase
  private lateinit var dao: SavedEventDao

  @Before
  fun setup() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    db = Room.inMemoryDatabaseBuilder(context, EventsDatabase::class.java).build()
    dao = db.savedEventDao()
  }

  @After
  fun tearDown() {
    db.close()
  }

  @Test
  fun savedEventDao_isAccessible_and_performsCrud() = runBlocking {
    val e =
        SavedEventEntity(
            id = "X1",
            userId = "userX",
            title = "TitleX",
            description = "DescX",
            dateSeconds = 10L,
            dateNanoseconds = 0,
            locationName = "LocX",
            locationLat = 0.1,
            locationLng = 0.2,
            tagsCsv = "",
            isPublic = true,
            ownerId = "ownerX",
            imageUrl = null,
            capacity = null,
            participantIdsCsv = "",
            savedAtSeconds = 55L)

    dao.insert(e)
    val list = dao.getSavedForUser("userX")
    assertEquals(1, list.size)
    assertEquals("X1", list[0].id)

    dao.delete("X1", "userX")
    val afterDelete = dao.getSavedForUser("userX")
    assertEquals(0, afterDelete.size)
  }
}
