package com.swent.mapin.ui.event

import org.junit.Assert.assertTrue
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Example local unit test, which will execute on the development machine (host).
 * Generated by AI.
 */

class AddEventUtilsTest {

  @Test
  fun `parseAndValidateStartEnd valid returns success`() {
    val res = parseAndValidateStartEnd("01/01/2025", "1300", "01/01/2025", "1500")
    assertTrue(res is ParseResult.Success)
    val success = res as ParseResult.Success
    // start < end
    assertTrue(success.end.toDate().after(success.start.toDate()))
  }

  @Test
  fun `parseAndValidateStartEnd endBeforeStart returns error`() {
    val res = parseAndValidateStartEnd("01/01/2025", "1500", "01/01/2025", "1400")
    assertTrue(res is ParseResult.Error)
    val err = res as ParseResult.Error
    assertEquals("end must be after start", err.message)
  }

  @Test
  fun `parseAndValidateStartEnd endEqualStart returns error`() {
    val res = parseAndValidateStartEnd("01/01/2025", "1500", "01/01/2025", "1500")
    assertTrue(res is ParseResult.Error)
    val err = res as ParseResult.Error
    assertEquals("end must be after start", err.message)
  }

  @Test
  fun `parseAndValidateStartEnd invalidParse returns error`() {
    val res = parseAndValidateStartEnd("invalid", "abcd", "01/01/2025", "1500")
    assertTrue(res is ParseResult.Error)
    val err = res as ParseResult.Error
    // message could be invalid start datetime
    assertEquals("invalid start datetime", err.message)
  }
}

